### ISSUE TITLE
请问一下为什么收藏单词后，excel中没有显示？

### ISSUE THREAD

**Issue by zhengzaifafeng** [Surbowl/oh-subtitle#10]
<img width="1245" alt="屏幕截图 2024-03-18 170948" src="https://github.com/Surbowl/oh-subtitle/assets/163835105/914f4cf1-22de-4f7a-b95b-13c0571513df">

**Comment by Surbowl** [comment]
@zhengzaifafeng 你好，请根据下列条件进行排查
  1. **OhSubtitle.exe** 与 **我的笔记.csv** 需在同一目录下
  2. 使用 **OhSubtitle.exe** 添加笔记时，不能有他程序同时在编辑 **我的笔记.csv**（Windows 系统不允许两个进程同时写文件，如需在添加笔记的同时查看 **我的笔记.csv** 内容，请用 Excel、WPS 等软件的只读模式打开）
  3. 检查添加笔记时 **OhSubtitle.exe** 是否有提示错误信息
  
希望上诉信息有所帮助，如果问题仍无法解决，请再次反馈，谢谢

**Comment by zhengzaifafeng** [comment]
前两个条件都满足并且添加笔记时 OhSubtitle.exe 也没有提示错误信息，还是添加不了：(

**Comment by zhengzaifafeng** [comment]
突然好了！（乐）
