### ISSUE TITLE
请问使用什么开发配置呢？比如VS版本，.Net版本，C#版本

### ISSUE THREAD

**Issue by CharlesLiaoO** [Surbowl/oh-subtitle#13]
请问使用什么开发配置呢？比如VS版本，.Net版本，C#版本
我使用VS 2017，.Net3.5，C#7.1，在`namespace OhSubtitle.Enums;`出现报错：`error CS1514: 应为 {`

**Comment by Surbowl** [comment]
你好，此项目使用 .NET 6.0 框架，您需要将 Visual Studio 升级到 Visual Studio 2022 或更高的版本才能进行开发

**Comment by CharlesLiaoO** [comment]
感谢，已成功编译
