### ISSUE TITLE
老哥,发布的为啥是源码,需要自己打包

### ISSUE THREAD

**Issue by JayLiuX** [Surbowl/oh-subtitle#6]

**Comment by Surbowl** [comment]
下载安装包：

百度网盘：https://pan.baidu.com/share/init?surl=upPT-eCSczfRLKlIoZF-Jg

提码：ydu7

**Comment by JayLiuX** [comment]
感谢老哥发的链接，不过我自己研究了一下，打包好了。后续有什么开发计划吗？我其实并不是用来看英语电影，是用来遮挡试卷的问题答案解析。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年10月7日 10:54
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Surbowl/oh-subtitle] 老哥,发布的为啥是源码,需要自己打包 (Issue #6)
        
      
    
  

下载安装包：
百度网盘：https://pan.baidu.com/share/init?surl=upPT-eCSczfRLKlIoZF-Jg
提码：ydu7

**Comment by Surbowl** [comment]
谢谢 JayLiuX 同学的支持
希望这个工具能保持简单干净，所以目前没有新增功能的计划；如果有比较好的建议也欢迎大家在 Issues 中提出，群策群力。
目前对鸿蒙比较感兴趣，后续可能会新建一个鸿蒙版的 repo
